package com.xinde.baggio.sandbox;

import android.content.Context;
import android.util.Log;

import com.xinde.baggio.Constant;
import com.xinde.baggio.SPKey.PropKey;
import com.xinde.baggio.util.IoUtil;
import com.xinde.baggio.util.SharedPref;

/**
 * author: Shawn
 * time  : 2018/7/6 10:53
 * desc  :
 * update: Shawn 2018/7/6 10:53
 */
public class BuildInfoGenerator extends AbstractGenerator {
    private static final String TAG = "BuildInfoGenerator";

    public BuildInfoGenerator(Context context) {
        super(context);
    }

    @Override
    public void run() {
        setBuildInfo();
        setBuildVersion();

        Log.i(TAG, TAG + " running...");
    }

    private void setBuildInfo() {
        SharedPref mySP = new SharedPref(this.context);
        // build about
        mySP.setSharedPref(PropKey.BRAND, "Huawei"); // 设备品牌
        mySP.setSharedPref(PropKey.BOARD, "msm8916"); // 主板
        mySP.setSharedPref(PropKey.CPU_ABI, "armeabi"); //  设备指令集名称 1
        mySP.setSharedPref(PropKey.CPU_ABI2, "armeabi-v7a"); //   设备指令集名称 2
        mySP.setSharedPref(PropKey.DEVICE, "hwG750-T01"); // 设备驱动名称
        mySP.setSharedPref(PropKey.DISPLAY, "R7c_11_151207"); //设备显示的版本包 固件版本
        mySP.setSharedPref(PropKey.FINGERPRINT, "Huawei/G750-T01/hwG750-T01:4.2.2/HuaweiG750-T01/C00B152:user/ota-rel-keys,release-keys");
        mySP.setSharedPref(PropKey.HARDWARE, "");
        mySP.setSharedPref(PropKey.ID, "KTU84P"); // 设备版本号
        mySP.setSharedPref(PropKey.MANUFACTURER, "HUAWEI"); // 设备制造商
        mySP.setSharedPref(PropKey.MODEL, "HUAWEI G750-T01"); // 手机的型号 设备名称
        mySP.setSharedPref(PropKey.PRODUCT, "hwG750-T01"); // 设备驱动名称
        mySP.setSharedPref(PropKey.BOOTLOADER, "unknown"); // 设备引导程序版本号
        mySP.setSharedPref(PropKey.HOST, "ubuntu-121-114"); // 设备主机地址
        mySP.setSharedPref(PropKey.TAGS, "release-keys"); // 设备标签
        mySP.setSharedPref(PropKey.TYPE, "user");
        mySP.setSharedPref(PropKey.USER, "smartcm"); // 设备版本类型
        mySP.setLongSharedPref(PropKey.TIME, System.currentTimeMillis());// 固件时间
        mySP.setSharedPref(PropKey.RADIO, "smartisan");
        mySP.setSharedPref(PropKey.SERIAL, "aee5060e"); // 串口序列号
        mySP.setSharedPref(PropKey.NAME, "mt6592"); // 设备硬件名称

        mySP.setSharedPref(PropKey.INCREMENTAL, "eng.root.20151207");
        mySP.setSharedPref(PropKey.RELEASE, "5.1");
        mySP.setSharedPref(PropKey.SDK, "22");
        mySP.setSharedPref(PropKey.CODENAME, "REL");
        mySP.setIntSharedPref(PropKey.SDK_INT, 22);

        mySP.setSharedPref(PropKey.ANDROID_ID, "fc4ad25f66d556647"); // android id
        mySP.setSharedPref(PropKey.DESCRIPTION, "jfltexx-user 4.3 JSS15J I9505XXUEML1 release-keys");
        mySP.setSharedPref(PropKey.BASE_BAND, "[MPSS.TA.2.3.c1-00167-8953_GEN_PACK-1.104080.1.124490.2");

        String content =
                "# begin build properties\n" +
                        "# autogenerated by buildinfo.sh\n" +
                        "ro.build.id=NMF26F\n" +
                        "ro.build.display.id=NMF26F dev-keys\n" +
                        "ro.build.version.incremental=10\n" +
                        "ro.build.version.sdk=22\n" +
                        "ro.build.version.preview_sdk=0\n" +
                        "ro.build.version.codename=REL\n" +
                        "ro.build.version.all_codenames=REL\n" +
                        "ro.build.version.release=5.1\n" +
                        "ro.build.version.security_patch=2018-04-05\n" +
                        "ro.build.version.base_os=\n" +
                        "ro.build.date=Fri Jun 22 01:23:08 CST 2018\n" +
                        "ro.build.date.utc=1529601788\n" +
                        "ro.build.type=user\n" +
                        "ro.build.user=smartcm\n" +
                        "ro.build.host=Softci19\n" +
                        "ro.build.tags=dev-keys\n" +
                        "ro.build.flavor=odin-user\n" +
                        "ro.product.model=XXX\n" +
                        "ro.product.brand=Rock\n" +
                        "ro.product.name=odin\n" +
                        "ro.product.device=odin\n" +
                        "ro.product.board=msm8953\n" +
                        "# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n" +
                        "# use ro.product.cpu.abilist instead.\n" +
                        "ro.product.cpu.abi=armabi\n" +
                        "ro.product.cpu.abilist=armeabi-v7a,armeabi\n" +
                        "ro.product.cpu.abilist32=armeabi-v7a,armeabi\n" +
                        "ro.product.cpu.abilist64=\n" +
                        "ro.product.manufacturer=Rock\n" +
                        "ro.product.locale=zh-CN\n" +
                        "ro.wifi.channels=\n" +
                        "ro.board.platform=msm8953\n" +
                        "# ro.build.product is obsolete; use ro.product.device\n" +
                        "ro.build.product=odin\n" +
                        "# Do not try to parse description, fingerprint, or thumbprint\n" +
                        "ro.build.description=odin-user 5.1 NMF26F 10 dev-keys\n" +
                        "ro.build.fingerprint=Rock/odin/odin:5.1/NMF26F/1529601788:user/dev-keys\n" +
                        "ro.build.characteristics=default\n" +
                        "persist.sys.timezone=Asia/Shanghai\n" +
                        "ro.voice_assistant_enable=1\n" +
                        "# end build properties\n" +
                        "#\n" +
                        "# from device/qcom/u3_common/system.prop\n" +
                        "#\n" +
                        "#\n" +
                        "# system.prop for msm8953\n" +
                        "#\n" +
                        "\n" +
                        "rild.libpath=/vendor/lib64/libril-qc-qmi-1.so\n" +
                        "rild.libargs=-d /dev/smd0\n" +
                        "persist.rild.nitz_plmn=\n" +
                        "persist.rild.nitz_long_ons_0=\n" +
                        "persist.rild.nitz_long_ons_1=\n" +
                        "persist.rild.nitz_long_ons_2=\n" +
                        "persist.rild.nitz_long_ons_3=\n" +
                        "persist.rild.nitz_short_ons_0=\n" +
                        "persist.rild.nitz_short_ons_1=\n" +
                        "persist.rild.nitz_short_ons_2=\n" +
                        "persist.rild.nitz_short_ons_3=\n" +
                        "ril.subscription.types=NV,RUIM\n" +
                        "DEVICE_PROVISIONED=1\n" +
                        "\n" +
                        "debug.sf.hw=0\n" +
                        "debug.egl.hw=0\n" +
                        "persist.hwc.mdpcomp.enable=true\n" +
                        "debug.mdpcomp.logs=0\n" +
                        "dalvik.vm.heapsize=36m\n" +
                        "dev.pm.dyn_samplingrate=1\n" +
                        "persist.demo.hdmirotationlock=false\n" +
                        "debug.enable.sglscale=1\n" +
                        "debug.gralloc.enable_fb_ubwc=1\n" +
                        "#ro.hdmi.enable=true\n" +
                        "#\n" +
                        "# system props for the cne module\n" +
                        "#\n" +
                        "persist.cne.feature=1\n" +
                        "\n" +
                        "#system props for the MM modules\n" +
                        "media.msm8956hw=0\n" +
                        "mm.enable.smoothstreaming=true\n" +
                        "mmp.enable.3g2=true\n" +
                        "media.aac_51_output_enabled=true\n" +
                        "av.debug.disable.pers.cache=1\n" +
                        "\n" +
                        "#codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP2PS MP2TS MP3 OGG QCP WAV FLAC AIFF APE\n" +
                        "mm.enable.qcom_parser=1048559\n" +
                        "\n" +
                        "#\n" +
                        "# system props for the data modules\n" +
                        "#\n" +
                        "ro.use_data_netmgrd=true\n" +
                        "persist.data.netmgrd.qos.enable=true\n" +
                        "persist.data.mode=concurrent\n" +
                        "\n" +
                        "#system props for time-services\n" +
                        "persist.timed.enable=true\n" +
                        "\n" +
                        "# SMARTISAN_BEGIN (0142441:Open and optimize ota feature)\n" +
                        "persist.radio.start_ota_daemon=1\n" +
                        "# SMARTISAN_END (0142441:Open and optimize ota feature)\n" +
                        "\n" +
                        "# SMARTISAN_BEGIN (CCM2005:CDMA SMS sent over TCH)\n" +
                        "# 2016-11-16 liulu:CDMA sms set over TCH M142877\n" +
                        "# 2017-02-08 liulu:Change the code comment M153983\n" +
                        "# CDMA sms sent over TCH\n" +
                        "persist.radio.force_on_dc=true\n" +
                        "# SMARTISAN_END (CCM2005:CDMA SMS sent over TCH)\n" +
                        "\n" +
                        "#\n" +
                        "# system prop for opengles version\n" +
                        "#\n" +
                        "# 196608 is decimal for 0x30000 to report major/minor versions as 3/0\n" +
                        "# 196609 is decimal for 0x30001 to report major/minor versions as 3/1\n" +
                        "ro.opengles.version=196609\n" +
                        "\n" +
                        "# System property for cabl\n" +
                        "ro.qualcomm.cabl=0\n" +
                        "\n" +
                        "#\n" +
                        "# System props for telephony\n" +
                        "# System prop to turn on CdmaLTEPhone always\n" +
                        "telephony.lteOnCdmaDevice=1\n" +
                        "\n" +
                        "#\n" +
                        "# System props for bluetooh\n" +
                        "# System prop to turn on hfp client\n" +
                        "bluetooth.hfp.client=1\n" +
                        "\n" +
                        "#Simulate sdcard on /data/media\n" +
                        "#\n" +
                        "persist.fuse_sdcard=true\n" +
                        "\n" +
                        "#System property for FM transmitter\n" +
                        "ro.fm.transmitter=false\n" +
                        "\n" +
                        "#Set composition for USB\n" +
                        "#persist.sys.usb.config=diag,serial_smd,rmnet_ipa,adb\n" +
                        "\n" +
                        "#Set read only default composition for USB\n" +
                        "#ro.sys.usb.default.config=diag,serial_smd,rmnet_ipa,adb\n" +
                        "\n" +
                        "#property to enable user to access Google WFD settings\n" +
                        "persist.debug.wfd.enable=1\n" +
                        "#property to enable VDS WFD solution\n" +
                        "persist.hwc.enable_vds=1\n" +
                        "\n" +
                        "#selects CoreSight configuration to enable\n" +
                        "persist.debug.coresight.config=stm-events\n" +
                        "\n" +
                        "#selects Console configuration to enable\n" +
                        "persist.console.silent.config=1\n" +
                        "\n" +
                        "#property for vendor specific library\n" +
                        "ro.vendor.gt_library=libqti-gt.so\n" +
                        "ro.vendor.at_library=libqti-at.so\n" +
                        "\n" +
                        "#property for game detection feature\n" +
                        "debug.enable.gamed=0\n" +
                        "\n" +
                        "#property to enable narrow search range for video encoding\n" +
                        "vidc.enc.disable_bframes=1\n" +
                        "vidc.disable.split.mode=1\n" +
                        "vidc.dec.downscalar_width=1920\n" +
                        "vidc.dec.downscalar_height=1088\n" +
                        "\n" +
                        "# disable PQ feature by default\n" +
                        "vidc.enc.disable.pq=true\n" +
                        "\n" +
                        "# Additional buffers shared between Camera and Video\n" +
                        "vidc.enc.dcvs.extra-buff-count=2\n" +
                        "\n" +
                        "# system property to accelerate Progressive Download using STA\n" +
                        "persist.mm.sta.enable=0\n" +
                        "\n" +
                        "#property to enable fingerprint\n" +
                        "persist.qfp=false\n" +
                        "\n" +
                        "#min/max cpu in core control\n" +
                        "ro.core_ctl_min_cpu=2\n" +
                        "ro.core_ctl_max_cpu=4\n" +
                        "\n" +
                        "#HWUI properties\n" +
                        "ro.hwui.texture_cache_size=72\n" +
                        "ro.hwui.layer_cache_size=48\n" +
                        "ro.hwui.r_buffer_cache_size=8\n" +
                        "ro.hwui.path_cache_size=32\n" +
                        "ro.hwui.gradient_cache_size=1\n" +
                        "ro.hwui.drop_shadow_cache_size=6\n" +
                        "ro.hwui.texture_cache_flushrate=0.4\n" +
                        "ro.hwui.text_small_cache_width=1024\n" +
                        "ro.hwui.text_small_cache_height=1024\n" +
                        "ro.hwui.text_large_cache_width=2048\n" +
                        "ro.hwui.text_large_cache_height=1024\n" +
                        "\n" +
                        "#Enable B service adj transition by default\n" +
                        "ro.sys.fw.bservice_enable=true\n" +
                        "ro.sys.fw.bservice_limit=5\n" +
                        "ro.sys.fw.bservice_age=5000\n" +
                        "\n" +
                        "#Memperf properties\n" +
                        "ro.memperf.lib=libmemperf.so\n" +
                        "ro.memperf.enable=false\n" +
                        "\n" +
                        "#Trim properties\n" +
                        "ro.sys.fw.use_trim_settings=true\n" +
                        "ro.sys.fw.empty_app_percent=50\n" +
                        "ro.sys.fw.trim_empty_percent=100\n" +
                        "ro.sys.fw.trim_cache_percent=100\n" +
                        "ro.sys.fw.trim_enable_memory=2147483648\n" +
                        "\n" +
                        "# Enable Delay Service Restart\n" +
                        "ro.am.reschedule_service=true\n" +
                        "\n" +
                        "#Optimal dex2oat threads for faster app installation\n" +
                        "ro.sys.fw.dex2oat_thread_count=4\n" +
                        "\n" +
                        "# Create zram disk\n" +
                        "ro.config.zram=true\n" +
                        "\n" +
                        "# set cutoff voltage to 3400mV\n" +
                        "ro.cutoff_voltage_mv=3400\n" +
                        "\n" +
                        "#set device emmc size\n" +
                        "ro.emmc_size=32GB\n" +
                        "\n" +
                        "#force HAL1 for below packages\n" +
                        "camera.hal1.packagelist=com.skype.raider,com.google.android.talk\n" +
                        "\n" +
                        "#Enable FR27607-RIL to send ONLINE cmd in bootup\n" +
                        "#persist.radio.poweron_opt=1\n" +
                        "\n" +
                        "#low power mode for camera\n" +
                        "camera.lowpower.record.enable=1\n" +
                        "\n" +
                        "#properties for limiting preview size in camera\n" +
                        "camera.display.umax=1920x1080\n" +
                        "camera.display.lmax=1280x720\n" +
                        "\n" +
                        "#set cutoff voltage to 3400mV\n" +
                        "ro.cutoff_voltage_mv=3400\n" +
                        "\n" +
                        "#enable drm service\n" +
                        "drm.service.enabled=true\n" +
                        "\n" +
                        "# Multisim config\n" +
                        "persist.radio.multisim.config=dsds\n" +
                        "# Default network mode\n" +
                        "ro.telephony.default_network=22\n" +
                        "# Ap defined ecclist\n" +
                        "ro.ril.ecclist=911,112,000,08,110,118,119,999,120,122\n" +
                        "# Redirecting party number feature\n" +
                        "persist.radio.redir_party_num=0\n" +
                        "# Enable RAT in operator searching result\n" +
                        "persist.radio.rat_on=combine\n" +
                        "#Report PS operator name for SRLTE\n" +
                        "persist.radio.sglte.eons_domain=ps\n" +
                        "# Enable report reject cause when REG rejected permanently\n" +
                        "persist.radio.lte_vrte_ltd=1\n" +
                        "# Default APN protocal\n" +
                        "ro.radio.apn.protocal=IPV4V6\n" +
                        "\n" +
                        "#Enable IMS\n" +
                        "persist.radio.calls.on.ims=true\n" +
                        "persist.radio.jbims=1\n" +
                        "persist.radio.vrte_logic=1\n" +
                        "\n" +
                        "# disable navigation bar\n" +
                        "qemu.hw.mainkeys=1\n" +
                        "\n" +
                        "#Headset button input device name\n" +
                        "ro.system.headsetinput=msm8953-snd-card-mtp Button Jack\n" +
                        "\n" +
                        "#codename\n" +
                        "ro.product.codename=odin\n" +
                        "\n" +
                        "#default phone color\n" +
                        "ro.housing.color=black\n" +
                        "\n" +
                        "#use external sdcard\n" +
                        "ro.storage.exsdcard=1\n" +
                        "\n" +
                        "# SMARTISAN_BEGIN (FR00200: Enable modem save power property)\n" +
                        "persist.radio.add_power_save=1\n" +
                        "# SMARTISAN_END (FR00200:Enable modem save power property)\n" +
                        "\n" +
                        "#\n" +
                        "# ADDITIONAL_BUILD_PROPERTIES\n" +
                        "#\n" +
                        "persist.smartisan.logs.enable=0\n" +
                        "persist.nfc.smartcard.config=SIM1,eSE1\n" +
                        "dalvik.vm.heapminfree=4m\n" +
                        "dalvik.vm.heapstartsize=16m\n" +
                        "dalvik.vm.heapgrowthlimit=192m\n" +
                        "dalvik.vm.heapsize=512m\n" +
                        "dalvik.vm.heaptargetutilization=0.75\n" +
                        "dalvik.vm.heapmaxfree=8m\n" +
                        "keyguard.no_require_sim=true\n" +
                        "ro.com.android.dataroaming=false\n" +
                        "ro.carrier=unknown\n" +
                        "ro.vendor.extension_library=libqti-perfd-client.so\n" +
                        "persist.radio.apm_sim_not_pwdn=1\n" +
                        "persist.radio.sib16_support=1\n" +
                        "persist.radio.custom_ecc=1\n" +
                        "persist.radio.multisim.config=dsds\n" +
                        "ro.frp.pst=/dev/block/bootdevice/by-name/config\n" +
                        "af.fast_track_multiplier=1\n" +
                        "audio_hal.period_size=192\n" +
                        "ro.qc.sdk.audio.fluencetype=fluence\n" +
                        "persist.audio.fluence.voicecall=true\n" +
                        "persist.audio.fluence.voicerec=false\n" +
                        "persist.audio.fluence.speaker=true\n" +
                        "tunnel.audio.encode=false\n" +
                        "audio.offload.buffer.size.kb=64\n" +
                        "audio.offload.min.duration.secs=30\n" +
                        "audio.offload.video=true\n" +
                        "audio.offload.pcm.16bit.enable=true\n" +
                        "audio.offload.pcm.24bit.enable=true\n" +
                        "audio.offload.track.enable=true\n" +
                        "audio.deep_buffer.media=true\n" +
                        "media.stagefright.audio.sink=280\n" +
                        "use.voice.path.for.pcm.voip=true\n" +
                        "audio.offload.multiaac.enable=true\n" +
                        "audio.dolby.ds2.enabled=false\n" +
                        "audio.dolby.ds2.hardbypass=false\n" +
                        "audio.offload.multiple.enabled=true\n" +
                        "audio.offload.passthrough=false\n" +
                        "ro.qc.sdk.audio.ssr=false\n" +
                        "audio.offload.gapless.enabled=true\n" +
                        "audio.safx.pbe.enabled=true\n" +
                        "audio.parser.ip.buffer.size=262144\n" +
                        "audio.playback.mch.downsample=true\n" +
                        "use.qti.sw.alac.decoder=true\n" +
                        "use.qti.sw.ape.decoder=true\n" +
                        "audio.pp.asphere.enabled=false\n" +
                        "voice.playback.conc.disabled=true\n" +
                        "voice.record.conc.disabled=false\n" +
                        "voice.voip.conc.disabled=true\n" +
                        "voice.conc.fallbackpath=deep-buffer\n" +
                        "persist.speaker.prot.enable=false\n" +
                        "qcom.hw.aac.encoder=true\n" +
                        "flac.sw.decoder.24bit.support=true\n" +
                        "persist.logd.size.main=320k\n" +
                        "ro.sys.usb.default.config=mtp,diag,mass_storage,accessory\n" +
                        "persist.service.cdrom.enable=1\n" +
                        "ro.crypto.fuse_sdcard=true\n" +
                        "ro.smartisan.version=6.0.0-201806220117-user-od\n" +
                        "ro.modversion=6.0.0-201806220117-user-od\n" +
                        "ro.config.ringtone=miDian.ogg\n" +
                        "ro.config.notification_sound=resurrect.ogg\n" +
                        "ro.config.alarm_alert=jiXieNaoZhong.ogg\n" +
                        "ro.config.mms_notification=resurrect.ogg\n" +
                        "ro.config.mail_send=smartisan_notifications02.ogg\n" +
                        "ro.config.idea_pills_ringtone=Bell.wav\n" +
                        "ro.config.calendar_notification=Tejat.ogg\n" +
                        "ro.product.cuptsm=SMARTISAN|ESE|01|02\n" +
                        "persist.sys.dalvik.vm.lib.2=libart.so\n" +
                        "dalvik.vm.isa.arm64.variant=generic\n" +
                        "dalvik.vm.isa.arm64.features=default\n" +
                        "dalvik.vm.isa.arm.variant=cortex-a53\n" +
                        "dalvik.vm.isa.arm.features=default\n" +
                        "net.bt.name=Android\n" +
                        "dalvik.vm.stack-trace-file=/data/anr/traces.txt\n" +
                        "ro.mdtp.package_name2=com.qualcomm.qti.securemsm.mdtp.MdtpDemo\n" +
                        "ro.smartisan.tag=sek\n" +
                        "ro.expect.recovery_id=0x106b605873b80e1e44e2a632b889e0d3f1c6a980000000000000000000000000\n";

        String path = String.format("%s/%s", Constant.FAKE_PATH, Constant.BUILD_PROP_NAME);
        IoUtil.writeFile(path, content);
    }


    private void setBuildVersion() {
        String path = String.format("%s/%s", Constant.FAKE_PATH, Constant.VERSION_FILE_NAME);
        String info = "Linux version 3.10.24-g8330ecc (builder@shawn) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Tue Sep 1 21:18:08 CST 2015\n";
        IoUtil.writeFile(path, info);
    }
}
